// Copyright (c) Thomas Nieto - All Rights Reserved
// You may use, distribute and modify this code under the
// terms of the MIT license.

using System.Text.Json;
using System.Text.Json.Nodes;

namespace OpenDsc.Server.Services;

public interface IJsonSchemaFormBuilder
{
    /// <summary>
    /// Parses a generated JSON Schema into a form definition for the parameter editor UI.
    /// </summary>
    SchemaFormDefinition BuildParameterForm(string schemaJson);
}

/// <summary>
/// Describes the set of fields available in the parameter form editor.
/// </summary>
public sealed class SchemaFormDefinition
{
    public required IReadOnlyList<SchemaFormField> Fields { get; init; }
    public bool HasSupportedFields => Fields.Any(f => f.Kind != SchemaFieldKind.Unsupported);
    public bool HasUnsupportedFields => Fields.Any(f => f.Kind == SchemaFieldKind.Unsupported);
}

/// <summary>
/// Represents a single editable parameter field parsed from the JSON Schema.
/// </summary>
public sealed class SchemaFormField
{
    public required string Name { get; init; }
    public required SchemaFieldKind Kind { get; init; }
    public bool IsRequired { get; init; }
    public string? Description { get; init; }
    public JsonNode? DefaultValue { get; init; }
    public decimal? Minimum { get; init; }
    public decimal? Maximum { get; init; }
    public IReadOnlyList<JsonNode?> EnumValues { get; init; } = [];
}

/// <summary>
/// Classifies the UI control kind for a schema-backed parameter field.
/// </summary>
public enum SchemaFieldKind
{
    Boolean,
    Integer,
    Number,
    String,
    Enum,
    /// <summary>
    /// Object and array fields are not editable in form mode.
    /// </summary>
    Unsupported
}

/// <summary>
/// Builds a <see cref="SchemaFormDefinition"/> from the JSON Schema generated by
/// <see cref="ParameterSchemaBuilder"/>. The schema is expected to have the
/// <c>{ "properties": { "parameters": { "properties": { ... } } } }</c> envelope
/// used for DSC parameter files.
/// </summary>
public sealed class JsonSchemaFormBuilder : IJsonSchemaFormBuilder
{
    public SchemaFormDefinition BuildParameterForm(string schemaJson)
    {
        if (string.IsNullOrWhiteSpace(schemaJson))
        {
            return new SchemaFormDefinition { Fields = [] };
        }

        JsonDocument doc;
        try
        {
            doc = JsonDocument.Parse(schemaJson);
        }
        catch (JsonException)
        {
            return new SchemaFormDefinition { Fields = [] };
        }

        using (doc)
        {
            var root = doc.RootElement;

            if (!root.TryGetProperty("properties", out var rootProperties) ||
                !rootProperties.TryGetProperty("parameters", out var parametersSchema))
            {
                return new SchemaFormDefinition { Fields = [] };
            }

            if (!parametersSchema.TryGetProperty("properties", out var parameterProperties))
            {
                return new SchemaFormDefinition { Fields = [] };
            }

            // Collect required parameter names from parameters.required
            var requiredNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (parametersSchema.TryGetProperty("required", out var requiredArray) &&
                requiredArray.ValueKind == JsonValueKind.Array)
            {
                foreach (var item in requiredArray.EnumerateArray())
                {
                    if (item.ValueKind == JsonValueKind.String && item.GetString() is { } name)
                    {
                        requiredNames.Add(name);
                    }
                }
            }

            var fields = new List<SchemaFormField>();
            foreach (var prop in parameterProperties.EnumerateObject())
            {
                fields.Add(BuildField(prop.Name, prop.Value, requiredNames.Contains(prop.Name)));
            }

            return new SchemaFormDefinition { Fields = fields };
        }
    }

    private static SchemaFormField BuildField(string name, JsonElement fieldSchema, bool isRequired)
    {
        var kind = DetermineKind(fieldSchema);

        string? description = null;
        if (fieldSchema.TryGetProperty("description", out var descEl) &&
            descEl.ValueKind == JsonValueKind.String)
        {
            description = descEl.GetString();
        }

        JsonNode? defaultValue = null;
        if (fieldSchema.TryGetProperty("default", out var defaultEl))
        {
            try
            {
                defaultValue = JsonNode.Parse(defaultEl.GetRawText());
            }
            catch (JsonException) { }
        }

        decimal? minimum = null;
        if (fieldSchema.TryGetProperty("minimum", out var minEl) &&
            minEl.TryGetDecimal(out var minVal))
        {
            minimum = minVal;
        }

        decimal? maximum = null;
        if (fieldSchema.TryGetProperty("maximum", out var maxEl) &&
            maxEl.TryGetDecimal(out var maxVal))
        {
            maximum = maxVal;
        }

        IReadOnlyList<JsonNode?> enumValues = [];
        if (fieldSchema.TryGetProperty("enum", out var enumEl) &&
            enumEl.ValueKind == JsonValueKind.Array)
        {
            var values = new List<JsonNode?>();
            foreach (var item in enumEl.EnumerateArray())
            {
                try
                {
                    values.Add(JsonNode.Parse(item.GetRawText()));
                }
                catch (JsonException)
                {
                    values.Add(null);
                }
            }
            enumValues = values;
        }

        return new SchemaFormField
        {
            Name = name,
            Kind = kind,
            IsRequired = isRequired,
            Description = description,
            DefaultValue = defaultValue,
            Minimum = minimum,
            Maximum = maximum,
            EnumValues = enumValues
        };
    }

    private static SchemaFieldKind DetermineKind(JsonElement fieldSchema)
    {
        // Enum takes precedence: if allowedValues were set, the schema has an "enum" keyword
        if (fieldSchema.TryGetProperty("enum", out var enumEl) &&
            enumEl.ValueKind == JsonValueKind.Array &&
            enumEl.GetArrayLength() > 0)
        {
            return SchemaFieldKind.Enum;
        }

        if (!fieldSchema.TryGetProperty("type", out var typeEl) ||
            typeEl.ValueKind != JsonValueKind.String)
        {
            return SchemaFieldKind.Unsupported;
        }

        return typeEl.GetString() switch
        {
            "string" => SchemaFieldKind.String,
            "integer" => SchemaFieldKind.Integer,
            "number" => SchemaFieldKind.Number,
            "boolean" => SchemaFieldKind.Boolean,
            _ => SchemaFieldKind.Unsupported
        };
    }
}
