@{
    ModuleVersion        = '0.5.1'
    GUID                 = '4f2f0f06-f2ea-4a90-aacf-d744de4d991b'
    Author               = 'Thomas Nieto'
    Copyright            = '(c) Thomas Nieto. All rights reserved.'
    Description          = 'PowerShell cmdlets for managing OpenDSC Server via OpenDsc.Client.'
    PowerShellVersion    = '7.6'
    CompatiblePSEditions = @('Core')
    RootModule           = 'OpenDsc.Client.Commands.dll'
    FunctionsToExport    = @()
    CmdletsToExport      = @(
        'Add-DscServerCompositeConfigurationChild',
        'Add-DscServerConfigurationFiles',
        'Add-DscServerGroupMember',
        'Add-DscServerNodeTag',
        'Connect-DscServer',
        'Disable-DscServerScopeType',
        'Disconnect-DscServer',
        'Enable-DscServerScopeType',
        'Get-DscServerCompositeConfiguration',
        'Get-DscServerCompositeConfigurationAvailableChildConfigurations',
        'Get-DscServerCompositeConfigurationAvailableMajorVersions',
        'Get-DscServerCompositeConfigurationGetCompositeConfigurations',
        'Get-DscServerCompositeConfigurationPermissions',
        'Get-DscServerCompositeConfigurationVersion',
        'Get-DscServerCompositeConfigurationVersions',
        'Get-DscServerConfiguration',
        'Get-DscServerConfigurationFile',
        'Get-DscServerConfigurationGetConfigurations',
        'Get-DscServerConfigurationParameterSchemaId',
        'Get-DscServerConfigurationPermissions',
        'Get-DscServerConfigurationRetentionSettings',
        'Get-DscServerConfigurationSettings',
        'Get-DscServerConfigurationVersionList',
        'Get-DscServerConfigurationVersions',
        'Get-DscServerGroup',
        'Get-DscServerGroupExternalGroupMappings',
        'Get-DscServerGroupGetGroups',
        'Get-DscServerGroupMemberCounts',
        'Get-DscServerGroupMembers',
        'Get-DscServerGroupRoleCounts',
        'Get-DscServerGroupRoles',
        'Get-DscServerNode',
        'Get-DscServerNodeAssignableCompositeConfigurations',
        'Get-DscServerNodeAssignableConfigurations',
        'Get-DscServerNodeAssignment',
        'Get-DscServerNodeAvailableCompositeConfigurations',
        'Get-DscServerNodeAvailableConfigurations',
        'Get-DscServerNodeConfigurationBundle',
        'Get-DscServerNodeConfigurationChecksum',
        'Get-DscServerNodeConfigurationManifest',
        'Get-DscServerNodeGetNodes',
        'Get-DscServerNodeReports',
        'Get-DscServerNodeScopeTypes',
        'Get-DscServerNodeScopeValues',
        'Get-DscServerNodeScopeValuesGetScopeValues',
        'Get-DscServerNodeStatusEvents',
        'Get-DscServerNodeTags',
        'Get-DscServerParameterActiveParameterForMajor',
        'Get-DscServerParameterAvailableMajorVersions',
        'Get-DscServerParameterContent',
        'Get-DscServerParameterMajorVersionSummaries',
        'Get-DscServerParameterNodeProvenance',
        'Get-DscServerParameterNodeResolution',
        'Get-DscServerParameterPermissions',
        'Get-DscServerParameterVersions',
        'Get-DscServerRegistrationKeyKeys',
        'Get-DscServerReport',
        'Get-DscServerReportGetReports',
        'Get-DscServerReportNode',
        'Get-DscServerRole',
        'Get-DscServerRoleGetRoles',
        'Get-DscServerRoleGroupCounts',
        'Get-DscServerRoleGroupsForRole',
        'Get-DscServerRoleUserCounts',
        'Get-DscServerScopeAllScopeTypesWithValues',
        'Get-DscServerScopeNodes',
        'Get-DscServerScopeParameters',
        'Get-DscServerScopeSummary',
        'Get-DscServerScopeType',
        'Get-DscServerScopeTypes',
        'Get-DscServerScopeTypeUsageCount',
        'Get-DscServerScopeUnrestrictedScopeValues',
        'Get-DscServerScopeValue',
        'Get-DscServerScopeValues',
        'Get-DscServerScopeValueUsageCount',
        'Get-DscServerSettingsPublicSettings',
        'Get-DscServerSettingsRetentionHistory',
        'Get-DscServerSettingsRetentionSettings',
        'Get-DscServerSettingsServerLcmDefaults',
        'Get-DscServerSettingsServerSettings',
        'Get-DscServerSettingsValidationSettings',
        'Get-DscServerUser',
        'Get-DscServerUserCurrentUser',
        'Get-DscServerUserEffectivePermissions',
        'Get-DscServerUserExternalLogin',
        'Get-DscServerUserGetUsers',
        'Get-DscServerUserGroupCounts',
        'Get-DscServerUserRoleCounts',
        'Get-DscServerUserRoles',
        'Grant-DscServerCompositeConfigurationPermission',
        'Grant-DscServerConfigurationPermission',
        'Grant-DscServerParameterPermission',
        'New-DscServerCompositeConfiguration',
        'New-DscServerCompositeConfigurationVersion',
        'New-DscServerCompositeConfigurationVersionFromExisting',
        'New-DscServerConfiguration',
        'New-DscServerConfigurationVersion',
        'New-DscServerConfigurationVersionFromExisting',
        'New-DscServerGroup',
        'New-DscServerGroupExternalGroupMapping',
        'New-DscServerParameter',
        'New-DscServerRegistrationKeyKey',
        'New-DscServerRole',
        'New-DscServerScopeType',
        'New-DscServerScopeValue',
        'New-DscServerUser',
        'Publish-DscServerCompositeConfigurationVersion',
        'Publish-DscServerConfigurationVersion',
        'Publish-DscServerParameter',
        'Remove-DscServerCompositeConfiguration',
        'Remove-DscServerCompositeConfigurationChild',
        'Remove-DscServerCompositeConfigurationVersion',
        'Remove-DscServerConfiguration',
        'Remove-DscServerConfigurationFile',
        'Remove-DscServerConfigurationSettings',
        'Remove-DscServerConfigurationVersion',
        'Remove-DscServerGroup',
        'Remove-DscServerGroupExternalGroupMapping',
        'Remove-DscServerGroupMember',
        'Remove-DscServerGroupRole',
        'Remove-DscServerNode',
        'Remove-DscServerNodeConfiguration',
        'Remove-DscServerNodeTag',
        'Remove-DscServerParameter',
        'Remove-DscServerRole',
        'Remove-DscServerScopeType',
        'Remove-DscServerScopeValue',
        'Remove-DscServerUser',
        'Remove-DscServerUserRole',
        'Reset-DscServerConfigurationRetentionSettings',
        'Reset-DscServerUserPassword',
        'Revoke-DscServerCompositeConfigurationPermission',
        'Revoke-DscServerConfigurationPermission',
        'Revoke-DscServerParameterPermission',
        'Revoke-DscServerRegistrationKeyKey',
        'Set-DscServerCompositeConfigurationChild',
        'Set-DscServerCompositeConfigurationChildUpdateChild',
        'Set-DscServerConfiguration',
        'Set-DscServerConfigurationEntryPoint',
        'Set-DscServerConfigurationFile',
        'Set-DscServerConfigurationRetentionSettings',
        'Set-DscServerConfigurationSettings',
        'Set-DscServerGroup',
        'Set-DscServerGroupMembers',
        'Set-DscServerGroupRole',
        'Set-DscServerGroupRoles',
        'Set-DscServerNodeConfiguration',
        'Set-DscServerNodeScopeValue',
        'Set-DscServerParameter',
        'Set-DscServerRegistrationKeyKey',
        'Set-DscServerRole',
        'Set-DscServerRoleGroupsForRole',
        'Set-DscServerScopeType',
        'Set-DscServerScopeTypes',
        'Set-DscServerScopeValue',
        'Set-DscServerSettingsRetentionSettings',
        'Set-DscServerSettingsServerLcmDefaults',
        'Set-DscServerSettingsServerSettings',
        'Set-DscServerSettingsValidationSettings',
        'Set-DscServerUser',
        'Set-DscServerUserPassword',
        'Set-DscServerUserRole',
        'Set-DscServerUserRoles',
        'Submit-DscServerReport',
        'Test-DscServerConfigurationAssigned',
        'Test-DscServerConfigurationVersionInUse',
        'Test-DscServerHealthConnect',
        'Test-DscServerNodeConfigurationChanged',
        'Test-DscServerUser',
        'Unlock-DscServerUser',
        'Update-DscServerRegistrationKeyKey'
    )
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('DSC', 'OpenDSC', 'Client', 'Server', 'PowerShell')
            ProjectUri = 'https://opendsc.dev'
            LicenseUri = 'https://github.com/opendsc/opendsc/blob/main/LICENSE'
        }
    }
}


